### ISSUE TITLE
Resultpage not always working due to index issues

### ISSUE THREAD

**Issue by wulsic** [wulsic/project-rekentuin#11]
Currently the number of the total made assignments is used for the foreach loop, BUT sometimes the sums don't start from position 1 from where they should start. 0410bc874877234f5247ad41d781ecdc6b09a9f6

**Comment by wulsic** [comment]
Well, referring the commit sadly doesn't work in the title.

**Comment by vietchinh** [comment]
https://github.com/wulsic/project-rekentuin/commit/b6664adcd1ae25e6843aff9a9126b2ba1d483c8c
