### ISSUE TITLE
Improving the result page.

### ISSUE THREAD

**Issue by vietchinh** [wulsic/project-rekentuin#5]
What I meant by this is right now it looks like this:
.... 1+1 2 .....

It needs to be changed into:

.... 1+1 = 2 .....

As functionality standpoint it is  almost done.
When you hit the result page, the array needs to be sorted.

**Comment by wulsic** [comment]
This should fix it for now: d8e7251ae1f13be1e9363c944a40551fa3b747c4
I don't think it's the best solution but it's just an idea

**Comment by vietchinh** [comment]
Good enough ^^, at least it didn't break the whole system.

Solved.
